<?php

namespace App\Models\Applicant;

use Illuminate\Database\Eloquent\Model;

/**
 * One application (tblapp_applications): an applicant's relationship with a
 * single job posting, as HR sees it.
 *
 * What a status means comes from config/applications.php, which mirrors the
 * applicant portal's copy. Closing, withdrawal, Not Selected and the Candidate
 * Pool all belong to an application — never to the applicant as a whole, whose
 * other applications carry on unaffected.
 */
class ApplicantApplication extends Model
{
    protected $connection = 'applicant';
    protected $table = 'tblapp_applications';

    // open_posting_id is generated by the database from closed_at; writing it
    // is an error, so it can never be mass-assigned.
    protected $guarded = ['id', 'open_posting_id'];

    // Stored values. They are data: see config/applications.php.
    public const APPLIED = 'Applied';
    public const DOCUMENTS_COMPLETE = 'Documents Complete';
    public const WITHDRAWN = 'Withdrawn';
    public const NON_RESPONSIVE = 'Non-Responsive';
    public const NOT_SELECTED = 'Not Selected';

    protected $casts = [
        'applied_at' => 'datetime',
        'closed_at' => 'datetime',
    ];

    public function applicant()
    {
        return $this->belongsTo(ApplicantPersonal::class, 'app_id', 'app_id');
    }

    /* ---------------------------------------------------------------------
     * The status table
     * ------------------------------------------------------------------- */

    /**
     * What a status means, or null for a status the table does not list.
     * Matched case-insensitively, the way the database compares the column, so
     * PHP and SQL never disagree about a row.
     *
     * @return array{closed: bool, candidate_pool: bool}|null
     */
    public static function statusDefinition(?string $status): ?array
    {
        $statuses = config('applications.statuses', []);
        $status = trim((string) $status);

        if (isset($statuses[$status])) {
            return $statuses[$status];
        }

        foreach ($statuses as $key => $definition) {
            if (strcasecmp($key, $status) === 0) {
                return $definition;
            }
        }

        return null;
    }

    /** Stored values of every status that ends an application. */
    public static function closedStatuses(): array
    {
        return self::statusesWhere('closed');
    }

    /** Stored values of every status that retains the candidate for that application. */
    public static function candidatePoolStatuses(): array
    {
        return self::statusesWhere('candidate_pool');
    }

    private static function statusesWhere(string $flag): array
    {
        return array_keys(array_filter(
            config('applications.statuses', []),
            fn ($definition) => !empty($definition[$flag])
        ));
    }

    /** Ended. An unlisted status is treated as open. */
    public function getIsClosedAttribute(): bool
    {
        return (bool) (self::statusDefinition($this->status)['closed'] ?? false);
    }

    /** In the Candidate Pool for THIS application only. */
    public function getInCandidatePoolAttribute(): bool
    {
        return (bool) (self::statusDefinition($this->status)['candidate_pool'] ?? false);
    }

    /**
     * For HR's information: the first day the applicant may apply to the same
     * posting again, if this application's outcome started a cooldown and it
     * has not ended. Counted exactly as the applicant portal enforces it
     * (zen-applicants App\Services\ReapplicationPolicy): months from
     * config/applications.php 'cooldowns', without overflow, from the start of
     * that day. The portal is where applying happens; this only reports it.
     */
    public static function cooldownEndsFor(?string $status, $closedAt): ?\Illuminate\Support\Carbon
    {
        if (!$closedAt) {
            return null;
        }

        foreach (config('applications.cooldowns', []) as $key => $rule) {
            if (strcasecmp($key, trim((string) $status)) === 0 && (int) ($rule['months'] ?? 0) > 0) {
                $ends = \Illuminate\Support\Carbon::parse($closedAt)
                    ->addMonthsNoOverflow((int) $rule['months'])
                    ->startOfDay();

                return now()->lessThan($ends) ? $ends : null;
            }
        }

        return null;
    }

    public function scopeOpen($query)
    {
        return $query->whereNotIn('status', self::closedStatuses());
    }

    public function scopeClosed($query)
    {
        return $query->whereIn('status', self::closedStatuses());
    }

    public function scopeInCandidatePool($query)
    {
        return $query->whereIn('status', self::candidatePoolStatuses());
    }
}
