<?php

namespace App\Models\Applicant;

use Illuminate\Database\Eloquent\Model;

/**
 * One application's document gate (tblapp_document_processes): a deadline for
 * the requests HR attaches to it, and an outcome.
 *
 * The documents and requests belong to the applicant and are reusable; the
 * process only points at requests. There is no attempt counter.
 *
 *   active          waiting on the requests attached to it
 *   complete        every attached request was accepted
 *   non_responsive  the deadline passed with requests unresolved
 *   withdrawn       its application was withdrawn
 *   not_selected    its application was marked Not Selected
 *
 * Everything but "active" is final. Whether the CANDIDATE is in the Candidate
 * Pool is a question about the application, not the process — see
 * ApplicantApplication.
 *
 * A process with no application (#16 and #17) predates the rule that every
 * process belongs to one; those rows are kept as history and are all final.
 */
class ApplicantDocumentProcess extends Model
{
    protected $connection = 'applicant';
    protected $table = 'tblapp_document_processes';

    // active_application_id is generated by the database; it is never written.
    protected $guarded = ['id', 'active_application_id'];

    public const ACTIVE = 'active';
    public const COMPLETE = 'complete';
    public const NON_RESPONSIVE = 'non_responsive';
    public const WITHDRAWN = 'withdrawn';
    public const NOT_SELECTED = 'not_selected';

    protected $casts = [
        'deadline_at' => 'datetime',
        'started_at' => 'datetime',
        'outcome_at' => 'datetime',
        'deadline_days' => 'integer',
    ];

    public function application()
    {
        return $this->belongsTo(ApplicantApplication::class, 'application_id');
    }

    public function requests()
    {
        return $this->hasMany(ApplicantDocumentRequest::class, 'process_id');
    }

    public function scopeActive($query)
    {
        return $query->where('status', self::ACTIVE);
    }

    /** Active processes the deadline job may close: overdue. */
    public function scopeOverdue($query, $asOf = null)
    {
        return $query->active()->where('deadline_at', '<', $asOf ?? now());
    }

    public function getIsActiveAttribute(): bool
    {
        return $this->status === self::ACTIVE;
    }

    public function getStatusLabelAttribute(): string
    {
        return config('applicant_documents.completion.statuses.' . $this->status, $this->status);
    }
}
